[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "api"
version = "0.0.1"
requires-python = ">=3.12"
license = {text = "MIT License"}

[tool.setuptools.packages.find]
where = ["."]
include = ["watsxn_trainup"]
exclude = ["logs"]
